import "dotenv/config";
import connectDB from "./infrastructure/db";

import Hotel from "./infrastructure/entities/Hotel";
import Location from "./infrastructure/entities/Location";
import { generateEmbedding } from "./application/utils/embeddings";
import stripe from "./infrastructure/stripe";

// Image URLs to reuse
const IMAGE_1 = "https://cf.bstatic.com/xdata/images/hotel/max1280x900/297840629.jpg?k=d20e005d5404a7bea91cb5fe624842f72b27867139c5d65700ab7f69396026ce&o=&hp=1";
const IMAGE_2 = "https://cf.bstatic.com/xdata/images/hotel/max1280x900/596257607.jpg?k=0b513d8fca0734c02a83d558cbad7f792ef3ac900fd42c7d783f31ab94b4062c&o=&hp=1";
const IMAGE_3 = "https://cf.bstatic.com/xdata/images/hotel/max1280x900/308797093.jpg?k=3a35a30f15d40ced28afacf4b6ae81ea597a43c90c274194a08738f6e760b596&o=&hp=1";
const IMAGE_4 = "https://cf.bstatic.com/xdata/images/hotel/max1280x900/84555265.jpg?k=ce7c3c699dc591b8fbac1a329b5f57247cfa4d13f809c718069f948a4df78b54&o=&hp=1";

// ~100-word description used for all hotels (static, no builder)
const DESCRIPTION = "Set in a vibrant city neighborhood, this contemporary hotel blends calm ambience with easy-going hospitality. Spacious rooms feature premium mattresses, blackout curtains, rain showers, and floor-to-ceiling windows with sweeping urban or harbor views. Guests unwind at a rooftop pool with loungers, a lively cocktail bar, and an all-day restaurant serving seasonal dishes and great coffee. Wellness facilities include a 24/7 fitness studio and serene spa suites; business travelers appreciate fast Wi-Fi, flexible workspaces, and well-equipped meeting rooms. Moments from cultural landmarks, parks, shops, and transit, it’s an effortless base for exploring. Thoughtful service, quiet luxury, and polished details define every stay.";

// Static list of 50 hotels
const hotels = [
  { name: "Grand Paris Vista", description: `In the heart of Paris, Grand Paris Vista layers Haussmann-era elegance with modern calm. Rooms feature plush bedding, marble bathrooms with rainfall showers, and soundproof windows opening to tree-lined boulevards. A rooftop terrace frames the Eiffel Tower; mornings begin with viennoiserie and café crème, evenings with Champagne at the salon bar. The bistro serves seasonal classics, while a petite spa, hammam, and 24/7 gym sustain busy days. Fiber Wi‑Fi, flexible meeting rooms, and attentive concierge make work and wandering effortless. Steps from the Seine, museums, and Métro, the hotel offers refined service, warm light, and a quietly luxurious base for unhurried discovery.`, image: IMAGE_1, location: "Paris, France", rating: 4.7, price: 160 },
  { name: "Royal Lyon Harbor", description: `Set along Lyon’s riverbanks, Royal Lyon Harbor overlooks the meeting of the Rhône and Saône. Rooms are restful and bright, with premium mattresses, deep showers, and balconies on select floors. Start with buttery praline brioche and strong coffee; end with Beaujolais at the wine lounge. An indoor pool, sauna, and compact spa restore after city walks. The brasserie riffs on bouchon favorites, while coworking tables and fast Wi‑Fi support productive mornings. Presqu’île squares, traboules, and silk workshops are a short stroll away. Culinary spirit, friendly service, and quiet comfort shape an easy tempo from dawn to dusk.`, image: IMAGE_2, location: "Lyon, France", rating: 4.6, price: 170 },
  { name: "Elegant Nice Gardens", description: `Moments from the Promenade des Anglais, Elegant Nice Gardens captures the Côte d’Azur’s breezy charm. Sun-splashed rooms pair linen textures with pale timbers; windows open to citrus courtyards perfumed with jasmine. A rooftop plunge pool and bar set the scene for golden-hour spritzes; breakfast is bright and seasonal. The spa’s steam room and treatment suites invite slow afternoons, while the gym keeps routines simple. Borrow bikes for seaside paths, wander markets in the old town, then return to shaded terraces and cool stone floors. Light, airy, and welcoming, the hotel feels made for effortless coastal days.`, image: IMAGE_3, location: "Nice, France", rating: 4.5, price: 180 },
  { name: "Majestic Bordeaux Plaza", description: `In stately Bordeaux, Majestic Bordeaux Plaza blends understated grandeur with wine-country warmth. Wrought-iron balconies, oak accents, and velvet seating soften spacious rooms; bathrooms feature walk-in rain showers and generous vanities. Tastings in the cellar spotlight regional châteaux; the brasserie serves modern takes on classic Girondin dishes. After tram-linked excursions, unwind in the sauna and massage suites or read by the library fireplace. Meeting salons are sunlit and equipped with crisp AV. Galleries, riverside paths, and grand squares unfold nearby. Hospitality here is attentive, unhurried, and quietly indulgent—ideal for savoring the city at an elegant pace.`, image: IMAGE_4, location: "Bordeaux, France", rating: 4.6, price: 190 },
  { name: "Serene Marseille Palace", description: `Facing the Vieux Port, Serene Marseille Palace carries a breezy, maritime spirit. Rooms echo the sea with soft blues and natural fibers; many open onto balconies with harbor glimpses. The terrace restaurant celebrates Provençal seafood and sun-soaked vegetables; a saltwater plunge pool and hammam complete easygoing wellness. Concierge-arranged Calanques boat trips and coastal hikes start at the door. Espresso arrives promptly, Wi‑Fi is swift, and meeting rooms accommodate quick briefings. At sunset, pastis and live acoustic sets welcome the evening. Mediterranean light, friendly service, and relaxed elegance make each stay refreshingly simple.`, image: IMAGE_1, location: "Marseille, France", rating: 4.4, price: 200 },
  { name: "Vibrant Toulouse Retreat", description: `In Toulouse’s pink-brick heart, Vibrant Toulouse Retreat mixes playful color with soothing textures. Quiet rooms offer plush beds, blackout drapes, rainfall showers, and thoughtful storage. Start the day under courtyard palms with flaky pastries; unwind later at the tapas bar or on the lantern-lit terrace. A 24/7 fitness room, compact spa cabin, and coworking lounges keep life balanced. Capitole squares, riverside paths, and aerospace museums are within easy reach by foot or bike. Warm smiles, good music, and relaxed lighting set a convivial tone that makes the hotel an inviting base for wandering and returning.`, image: IMAGE_2, location: "Toulouse, France", rating: 4.5, price: 210 },
  { name: "Urban Sydney Lodge", description: `Overlooking glittering harbor inlets, Urban Sydney Lodge brings a polished coastal mood to spacious, light-filled rooms. Expect premium bedding, walk-in showers, and quiet climate control. The infinity pool and deck stretch into long, sunny afternoons; evenings gather at the cocktail bar and wood-fire grill. Ferries and light rail sit moments away for effortless exploring. Wellness includes a capable gym and treatment rooms, while event spaces and fiber Wi‑Fi support focused work. Concierge surf lessons and coastal walks round out the day. Easygoing service and warm Australian hospitality define a stay made for sea-breeze living.`, image: IMAGE_3, location: "Sydney, Australia", rating: 4.8, price: 300 },
  { name: "Coastal Melbourne Suites", description: `Tucked near laneways and galleries, Coastal Melbourne Suites combines apartment-style convenience with boutique charm. Suites include kitchenettes, deep sofas, and espresso setups; windows frame river light and city textures. A heated lap pool, sauna, and compact spa center urban wellness. The lobby bar pours natural wines and spins vinyl in the evenings; mornings begin with proper flat whites. Coworking tables and fast Wi‑Fi suit long stays. Stroll to markets, tram stops, and river trails with a house-made map of local favorites. Creative energy, calm interiors, and thoughtful amenities keep everything relaxed and easy.`, image: IMAGE_4, location: "Melbourne, Australia", rating: 4.7, price: 280 },
  { name: "Heritage Brisbane Resort", description: `Beside the Brisbane River, Heritage Brisbane Resort leans into subtropical ease: palm-dappled courtyards, a lagoon-style pool with cabanas, and breezy verandas. Sunlit rooms feature plush beds, rainfall showers, and intuitive tech; select suites add daybeds and balconies. The restaurant celebrates coastal produce, the bar spotlights Queensland craft beers, and the kids club keeps families smiling. A 24/7 gym, spa suites, and flexible meeting spaces balance play and productivity. Borrow bikes for river paths or ferry to South Bank. Warm service, river views, and relaxed refinement make everyday moments feel like holiday time.`, image: IMAGE_1, location: "Brisbane, Australia", rating: 4.6, price: 260 },
  { name: "Panorama Perth Inn", description: `Watching sunsets over the Swan River, Panorama Perth Inn layers bright timbers, linen textures, and abundant daylight. A rooftop cinema and petite plunge pool set a playful tone; the terrace café serves seasonal plates and excellent coffee. Rooms deliver blackout calm, generous showers, and efficient storage. Jog through Kings Park at dawn, then return to coworking nooks and quick Wi‑Fi. Evenings drift with local wines under a soft coastal breeze. The vibe is friendly and unpretentious, making city days feel unhurried and genuinely restorative.`, image: IMAGE_2, location: "Perth, Australia", rating: 4.5, price: 240 },
  { name: "Grand Adelaide Residence", description: `Grand Adelaide Residence sits between leafy parklands and the bustling Central Market, pairing contemporary calm with South Australian warmth. Spacious rooms feature plush bedding, rain showers, and Juliet balconies on select floors. The open-kitchen restaurant champions Barossa and Adelaide Hills produce; the bar leans toward small-batch gins and crisp whites. A modest gym, sauna, and serene treatment rooms invite slow resets after gallery strolls and coastal drives. Meeting salons are bright and functional, supported by fast Wi‑Fi. Friendly hosts point you toward laneways, vineyards, and beaches. Easygoing, polished, and generous—made for longer, restorative stays.`, image: IMAGE_3, location: "Adelaide, Australia", rating: 4.4, price: 230 },
  { name: "Royal Gold Coast Vista", description: `Beach mornings and golden-hour evenings frame days at Royal Gold Coast Vista. Wake to the hush of surf, step onto the boardwalk, and claim a cabana by the palm‑lined pool. Rooms are light and coastal, some with balconies and daybeds; bathrooms deliver powerful rain showers and soft towels. Borrow boards, book a couples’ massage, or follow our sunrise run route. The all-day restaurant highlights seafood and tropical fruit, while the terrace bar hosts acoustic sets. Families love the splash zone; service is warm and effortless. Sun, salt, and easy smiles set the rhythm.`, image: IMAGE_4, location: "Gold Coast, Australia", rating: 4.6, price: 250 },
  { name: "Elegant Tokyo Harbor", description: `Sleek lines and quiet light define Elegant Tokyo Harbor, gazing across Tokyo Bay. Rooms offer deep soaking tubs, blackout serenity, and floor‑to‑ceiling windows with skyline or water views. A tea lounge hosts afternoon rituals; the restaurant treats seasonal ingredients with restrained elegance. Wellness spans a 24/7 gym and onsen‑inspired baths, while meeting suites ensure crisp acoustics and seamless tech. Steps from promenades and efficient rail, the hotel becomes a restorative base. Service is precise yet warm, and the city’s neon softens to a hush each night.`, image: IMAGE_1, location: "Tokyo, Japan", rating: 4.8, price: 320 },
  { name: "Majestic Osaka Gardens", description: `A tranquil courtyard anchors Majestic Osaka Gardens, moments from Dotonbori’s bright signs. Rooms are spacious by local standards, with plush bedding, rainfall showers, and thoughtful wardrobes. Slip into onsen‑style suites to unwind, then sample citrus highballs and savory small plates at the lobby bar. The gym and spa are compact yet polished; Wi‑Fi is swift. Our concierge maps late‑night ramen and morning markets. Between bustle and calm, the hotel offers a soft landing that invites long, contented stays.`, image: IMAGE_2, location: "Osaka, Japan", rating: 4.7, price: 290 },
  { name: "Serene Kyoto Plaza", description: `Near lantern‑lit alleys and temple paths, Serene Kyoto Plaza favors natural woods, woven textures, and low, contemplative lighting. Rooms provide tatami‑inspired touches, soaking tubs, and exceptional sound insulation for deep rest. Dine on kaiseki‑inspired plates, or sip whisked matcha in a reading lounge with a pocket‑garden view. A petite spa offers aromatherapy and stone baths; the gym supports simple routines. Shrines at dawn, tea at dusk—the cadence feels mindful, gentle, and beautifully unhurried.`, image: IMAGE_3, location: "Kyoto, Japan", rating: 4.7, price: 280 },
  { name: "Vibrant Sapporo Palace", description: `Vibrant Sapporo Palace embraces northern seasons. After ski days or park picnics, restore in hot‑stone baths and a cedar‑scented sauna. Rooms are snug yet elevated, with plush duvets, humidifiers, and blackout calm. The bar showcases Hokkaido craft beers and warming snacks; the restaurant leans hearty and seasonal. A gear room stores skis, boards, and winter layers with ease. Transit, shopping streets, and festival grounds sit nearby. Comfort, warmth, and friendly guidance make winter and summer stays equally inviting.`, image: IMAGE_4, location: "Sapporo, Japan", rating: 4.5, price: 240 },
  { name: "Urban Fukuoka Retreat", description: `By canals and leafy promenades, Urban Fukuoka Retreat places ramen counters, seafood markets, and waterfront walks moments away. Rooms feature generous showers, plush beds, and airy palettes for relaxed mornings. Borrow a bike, book a massage, or work from the sunlit lounge with coffee on tap. The gym is compact and useful; meeting pods suit quick sessions. Evenings drift between the noodle bar and laid‑back terrace. Gentle service and thoughtful amenities make exploring and unwinding equally effortless.`, image: IMAGE_1, location: "Fukuoka, Japan", rating: 4.4, price: 230 },
  { name: "Coastal Yokohama Lodge", description: `Facing Minato Mirai, Coastal Yokohama Lodge brings ferris‑wheel vistas, harbor strolls, and breezy rooms with floor‑to‑ceiling glass. Families appreciate an airy playroom and interconnecting suites; couples linger on balconies as ships slide by. The café serves bright breakfasts and seasonal bowls; evenings favor sashimi and crisp lagers. A petite spa and gym keep wellness on track. Trains, promenades, and galleries are steps away. Calm service, salt air, and soft linens lend a relaxed coastal rhythm to every day.`, image: IMAGE_2, location: "Yokohama, Japan", rating: 4.6, price: 260 },
  { name: "Heritage New York Suites", description: `Rising above Fifth Avenue, Heritage New York Suites pairs skyline views with soundproof serenity. Studio-style suites blend mid‑century lines with rich woods and plush textiles; marble bathrooms feature walk‑in rain showers. The speakeasy pours classic cocktails; the restaurant serves elevated comfort late into the night. A Peloton‑equipped fitness studio, sauna, and quiet lounge sustain wellness. Meeting rooms offer crisp acoustics and seamless tech. Broadway, museums, and Central Park are close, yet your room remains a cocoon of stillness and warm light, perfect for deep rest between dazzling city days.`, image: IMAGE_3, location: "New York, United States", rating: 4.9, price: 350 },
  { name: "Panorama Los Angeles Resort", description: `With hillside views stretching to the Hollywood sign, Panorama Los Angeles Resort feels like a private, sun‑drenched escape. Poolside cabanas, a palm‑lined terrace, and a market‑fresh restaurant set an easy rhythm. Rooms pair gauzy curtains with timber accents, spa‑like baths, and blackout shades for late starts. A yoga lawn, compact spa, and modern gym nurture balance, while valet, EV charging, and car rentals simplify roaming. Our concierge books studio tours and coastal drives. Effortless service and warm West Coast light define the vibe from sunrise to golden hour.`, image: IMAGE_4, location: "Los Angeles, United States", rating: 4.7, price: 310 },
  { name: "Grand Chicago Inn", description: `Steps from the Riverwalk, Grand Chicago Inn marries Midwestern warmth with modern polish. Rooms are generous, with plush beds, deep soaking tubs, and city views through tall windows. The indoor pool and sauna make winters comfortable; the bar serves local brews and weekend jazz. The bistro nods to deep‑dish comfort alongside bright seasonal plates. Meeting spaces are functional and sunlit; Wi‑Fi is quick and steady. Architecture tours, theaters, and museums are within a short stroll. Thoughtful details—from heated floors to soft robes—turn busy days into slow, satisfying evenings.`, image: IMAGE_1, location: "Chicago, United States", rating: 4.6, price: 300 },
  { name: "Royal Miami Residence", description: `Royal Miami Residence captures South Beach energy with pastel umbrellas, a palm‑ringed pool, and a beach club minutes away. Suites are breezy and light, with terrazzo accents, rainfall showers, and blackout calm. The rooftop hosts sunrise yoga and sunset DJ sets; the café presses tropical juices and Cuban coffee. A compact spa refreshes between ocean dips and late nights. Concierge beach setups, bicycles, and easy valet keep days carefree. Lively, colorful, and refined, the hotel blends seaside fun with polished comfort for memorable escapes.`, image: IMAGE_2, location: "Miami, United States", rating: 4.5, price: 270 },
  { name: "Elegant San Francisco Vista", description: `Perched above the bay, Elegant San Francisco Vista offers sweeping water views and calm interiors tuned to the city’s microclimates. Expect plush bedding, soft throws, radiant bathroom heat, and mist‑friendly ventilation. The restaurant turns farmers’ market produce into bright, modern plates; the café keeps coffee excellent. Coworking tables, meeting pods, and quick Wi‑Fi support flexible days. Cable cars, waterfront paths, and characterful neighborhoods are close. Quiet luxury, thoughtful warmth, and a strong sense of place define each night.`, image: IMAGE_3, location: "San Francisco, United States", rating: 4.7, price: 330 },
  { name: "Majestic Seattle Harbor", description: `Majestic Seattle Harbor overlooks working piers and ferry crossings on the sound. Rooms celebrate Pacific Northwest textures—wool throws, cedar accents, and cozy lighting—framed by big windows and moody skies. The espresso bar fuels early starts; the seafood grill highlights salmon, oysters, and foraged flavors. A sauna and fitness suite restore after rain‑soaked adventures. Pike Place Market, galleries, and water trails lie minutes away. The pace is unhurried, the service attentive, and the atmosphere quietly maritime.`, image: IMAGE_4, location: "Seattle, United States", rating: 4.6, price: 290 },
  { name: "Serene Rome Gardens", description: `Serene Rome Gardens settles into vine-draped lanes near sunlit piazzas and baroque fountains. A leafy courtyard hosts long breakfasts and evening spritzes, while a rooftop reveals terracotta rooftops and domes. Rooms combine carved stone and crisp linens with rainfall showers and quiet climate control. The espresso bar hums from dawn; the trattoria favors Roman classics with seasonal produce. Concierge arranges museum entries, Vespa rentals, and hidden tours. Warm service, historic texture, and restful spaces make returning feel like coming home.`, image: IMAGE_1, location: "Rome, Italy", rating: 4.7, price: 260 },
  { name: "Vibrant Milan Plaza", description: `Next to fashion houses and design studios, Vibrant Milan Plaza merges modern glamour with welcoming ease. The cocktail bar serves aperitivo with house-made bites; the kitchen celebrates northern Italian flavors with a fresh twist. Rooms balance sleek lines and warm textures, with sound insulation and generous showers. A sauna, gym, and treatment room deliver quick wellness resets between shows and shopping. Courtyard seating is perfect for people-watching and late conversations. Chic, lively, and friendly, it’s a polished base for creative days.`, image: IMAGE_2, location: "Milan, Italy", rating: 4.6, price: 270 },
  { name: "Urban Venice Palace", description: `On a quiet canal with a private jetty, Urban Venice Palace offers a refined hideaway minutes from the bustle. Glide by gondola to dinner, then return to candlelit dining and softly lit salons. Rooms reveal timber beams, Murano-glass details, and serene beds. Enjoy breakfast on the water terrace, explore hidden churches, and linger over cicchetti in the bar. A tiny spa, thoughtful concierge, and hushed hallways allow time to stretch. Romance, craftsmanship, and gentle service shape the mood.`, image: IMAGE_3, location: "Venice, Italy", rating: 4.6, price: 280 },
  { name: "Coastal Florence Retreat", description: `Coastal Florence Retreat gazes toward the Arno and artisan studios. Mornings bring terrace breakfasts and cappuccinos; afternoons drift between galleries and a petite spa with steam. Rooms pair soft linens with stone floors and handmade details; showers are powerful and comforting. The bistro serves Tuscan plates and bright salads; the lounge pours Chianti by the glass. Artists, wanderers, and weekenders feel at ease. Quiet elegance, human warmth, and a strong sense of place define the stay.`, image: IMAGE_4, location: "Florence, Italy", rating: 4.5, price: 250 },
  { name: "Heritage Naples Lodge", description: `Heritage Naples Lodge peers across the bay to Vesuvius, blending rustic arches with soothing modern comforts. Rooms offer generous beds, balconies, and breezy air; bathrooms feature rain showers and local stone. Join a pizza-making class, relax in the courtyard, or head to Pompeii with arranged transport. The restaurant leans into Campanian flavors, and the bar serves limoncello spritzes at sunset. A modest gym and spa keep routines steady. Sunlit, flavorful, and friendly—each day feels richly lived.`, image: IMAGE_1, location: "Naples, Italy", rating: 4.4, price: 230 },
  { name: "Panorama Turin Suites", description: `Beneath Alpine horizons, Panorama Turin Suites presents wide-windowed rooms, snug reading corners, and winter-ready comforts. A chocolate lounge and evening cinema space become cozy rituals; the trattoria brings Piedmont specialties to the table. Trams and museums sit nearby. A sauna, compact gym, and massage cabin restore after snow or sun. Attentive staff keep the pace relaxed and smooth. It’s an inviting base for grand boulevards and tucked-away cafés.`, image: IMAGE_2, location: "Turin, Italy", rating: 4.5, price: 240 },
  { name: "Grand Barcelona Resort", description: `Grand Barcelona Resort rises within the Eixample grid, where a rooftop pool and terrace watch the city’s geometry fade into sea breezes. Tapas flow alongside natural wines in the bar; the restaurant celebrates Catalan produce. Rooms feature sculptural headboards, rainfall showers, soft robes, and sound-softened windows. Morning jogs trace Passeig de Gràcia; afternoons wander to Gaudí works and the beach. Sun, creativity, and a warm welcome infuse every moment, balanced by thoughtful calm at day’s end.`, image: IMAGE_3, location: "Barcelona, Spain", rating: 4.8, price: 300 },
  { name: "Royal Madrid Inn", description: `Near Retiro Park and grand boulevards, Royal Madrid Inn pairs marble poise with lively city rhythm. Rooms are quiet and cool, with plush bedding and powerful showers. The bar hosts a daily vermouth hour; the kitchen updates Castilian classics late into the night. A sauna and fitness room anchor wellness, while meeting spaces feel bright and confident. Museums, shops, and cafés ring the neighborhood. Cultured yet playful, it invites late dinners and slow mornings.`, image: IMAGE_4, location: "Madrid, Spain", rating: 4.6, price: 270 },
  { name: "Elegant Seville Residence", description: `Fragrant with orange blossom, Elegant Seville Residence gathers courtyards and arcades around a lantern-lit heart. Rooms stay cool and quiet with carved wood, patterned tiles, and plush beds. A shaded plunge pool and rooftop lounge welcome languid afternoons; the bar hosts flamenco guitar sets. Breakfast favors Andalusian specialties; evenings lean toward tapas and fino sherry. A small spa and efficient gym keep balance. Warm, melodic, and romantic, it suits aimless strolling and restful returns.`, image: IMAGE_1, location: "Seville, Spain", rating: 4.5, price: 250 },
  { name: "Majestic Valencia Vista", description: `Neighboring the City of Arts and Sciences, Majestic Valencia Vista marries futuristic curves with Mediterranean ease. Borrow bikes for the Turia gardens, then cool off in the rooftop pool. Rooms offer sleek furnishings, rainfall showers, and terraces that catch evening light. The restaurant embraces market-fresh seafood and citrus; the bar mixes herbal, sunlit cocktails. A compact spa, modern gym, and quick Wi‑Fi keep days balanced between beach and culture.`, image: IMAGE_2, location: "Valencia, Spain", rating: 4.6, price: 260 },
  { name: "Serene Granada Harbor", description: `With the Alhambra’s outline beyond, Serene Granada Harbor blends Moorish motifs with contemporary calm. Rooms offer plush beds, deep showers, and quiet air for afternoon siestas. The tea room perfumes the lobby with mint; the restaurant serves Andalusian flavors with a modern touch. Evenings unfold on the terrace beneath a scatter of stars. A petite spa and sauna restore after steep-street wanderings. Attentive service keeps the pace gentle and unhurried.`, image: IMAGE_3, location: "Granada, Spain", rating: 4.4, price: 230 },
  { name: "Vibrant Bilbao Gardens", description: `Vibrant Bilbao Gardens rests by the river, footsteps from the Guggenheim’s shimmering curves. Inside, greenery softens modern lines; rooms are restful, with plush bedding, blackout curtains, and generous showers. Pintxos and txakoli define the bar; the kitchen explores Basque flavors. A small gym, sauna, and treatment room offer quick resets. Walk the riverfront at sunset, browse galleries, and end with mellow conversation. Artful, friendly, and bright—this is Bilbao at ease.`, image: IMAGE_4, location: "Bilbao, Spain", rating: 4.5, price: 240 },
  { name: "Urban London Plaza", description: `Urban London Plaza places you by the Thames, theaters, and markets, while preserving hush and calm within. Rooms feature plush beds, walk‑in showers, heated floors, and soft lighting for unwinding. The brasserie serves British classics with seasonal flair; the bar mixes proper cocktails. A capable gym and compact spa steady routines; a club lounge supports focused work with fiber Wi‑Fi. Black‑taxi access, Underground links, and strolls along the river make exploring simple. Polished, warm, and quietly luxe from lobby to room.`, image: IMAGE_1, location: "London, United Kingdom", rating: 4.8, price: 320 },
  { name: "Coastal Manchester Palace", description: `Coastal Manchester Palace nods to canals and music halls with industrial‑chic details and generous comfort. Rain‑friendly touches—drying racks, cozy robes, and comforting tea—make city showers welcome. Rooms provide plush mattresses, blackout serenity, and strong showers. The restaurant grills Northern favorites; the bar keeps live sets intimate. A wellness suite, small spa, and capable gym keep balance amid the buzz. Friendly staff, walkable quarters, and tram links set an unhurried rhythm.`, image: IMAGE_2, location: "Manchester, United Kingdom", rating: 4.6, price: 270 },
  { name: "Heritage Edinburgh Retreat", description: `Overlooking castle ridges and cobbled closes, Heritage Edinburgh Retreat offers tartan touches, afternoon tea, and a whisky snug with curated flights. Rooms feel warm and layered, with wool throws, deep mattresses, and rainfall showers. After exploring, unwind in the sauna or book a massage. Breakfast favors hearty Scottish classics; evenings bring candlelight and quiet conversation. Museums, gardens, and theaters cluster nearby. Storied, soothing, and unmistakably Edinburgh.`, image: IMAGE_3, location: "Edinburgh, United Kingdom", rating: 4.6, price: 260 },
  { name: "Panorama Bristol Lodge", description: `Along the harborside, Panorama Bristol Lodge blends maritime heritage with playful design. Rooms frame bridge and water views; families appreciate spacious layouts and thoughtful kid amenities. The lobby café serves excellent coffee; the bistro highlights West Country produce. A small pool, steam, and gym keep wellness flowing. Street art tours, galleries, and markets are within an easy stroll. Friendly, creative, and colorful—like the city itself.`, image: IMAGE_4, location: "Bristol, United Kingdom", rating: 4.5, price: 240 },
  { name: "Grand Liverpool Suites", description: `Grand Liverpool Suites faces the Mersey, weaving the city’s musical heritage through lounges and suites. Expect generous beds, rainfall showers, kitchenettes in many rooms, and hushed acoustics for deep rest. The pool and sauna welcome evening unwinds; the bar spins classic vinyl and pours local ales. Concierge routes make Anfield and waterfront museums easy. Warm, nostalgic, and quietly refined, it suits weekends and long stays alike.`, image: IMAGE_1, location: "Liverpool, United Kingdom", rating: 4.5, price: 250 },
  { name: "Royal Birmingham Resort", description: `Royal Birmingham Resort neighbors canals and the Jewellery Quarter, pairing modern ease with crafted details. Rooms deliver plush bedding, walk‑in showers, and flexible desks. The Indian grill and cocktail bar hum at dinner; breakfast leans hearty and bright. A sauna, capable gym, and small spa help travelers reset. Meetings run smoothly with strong Wi‑Fi and daylight. Shops, galleries, and venues cluster nearby for simple, lively evenings.`, image: IMAGE_2, location: "Birmingham, United Kingdom", rating: 4.4, price: 230 },
  { name: "Elegant Toronto Inn", description: `Overlooking the CN Tower and lakefront, Elegant Toronto Inn connects easily to PATH for winter convenience. Rooms provide plush duvets, espresso machines, heated bathroom floors, and serene lighting. The café roasts attentively; the restaurant blends global flavors with Canadian ingredients. A compact spa, sauna, and gym maintain balance, while meeting pods support quick work sessions. Skating rinks, markets, and theaters lie close by. Calm, bright, and quietly upscale—great for business and weekend wandering alike.`, image: IMAGE_3, location: "Toronto, Canada", rating: 4.7, price: 280 },
  { name: "Majestic Vancouver Residence", description: `Between mountains and ocean, Majestic Vancouver Residence invites movement and stillness. Borrow seawall bikes, stretch in morning yoga, and return to a pool ringed by evergreens. Rooms feature natural textures, large windows, and deep showers; many include balconies for fresh air. The kitchen celebrates coastal produce; the bar pours crisp wines and local craft beers. Sustainability is considered at every turn. Fresh, outdoorsy, and restorative—ideal for long, replenishing stays.`, image: IMAGE_4, location: "Vancouver, Canada", rating: 4.6, price: 270 },
  { name: "Serene Montreal Vista", description: `Serene Montreal Vista blends European charm with North American ease in cobblestoned quarters. Suites feel layered and warm, with plush rugs, soft lighting, and blackout drapes. A terrace fireplace extends evenings; winter months bring hot chocolate and comforting stews. The spa’s sauna and treatment rooms revive after snowy walks; the gym keeps routines simple. Cafés, galleries, and river paths lie just beyond the door. Quiet, atmospheric, and welcoming year‑round.`, image: IMAGE_1, location: "Montreal, Canada", rating: 4.5, price: 250 },
  { name: "Vibrant Calgary Harbor", description: `By the Bow River, Vibrant Calgary Harbor frames mountain horizons on clear days. Rooms offer plush bedding, generous showers, and calm palettes. The heated pool, sauna, and hot tub keep winters pleasant; the grill celebrates Alberta beef with bright seasonal sides. Stampede energy meets easygoing hospitality in the bar’s live‑music nights. Trails, markets, and galleries are a short stroll away. Friendly, capable, and comfortable—made for all seasons.`, image: IMAGE_2, location: "Calgary, Canada", rating: 4.4, price: 230 },
  { name: "Urban Ottawa Gardens", description: `Urban Ottawa Gardens neighbors Parliament and riverside paths, marrying quiet rooms with leafy lounges. Expect plush beds, walk‑in showers, espresso sets, and steady Wi‑Fi. A library lounge encourages long reads; the restaurant focuses on seasonal Canadian produce. A small pool and gym keep days balanced. Tulip season paints the city outside; winter lights sparkle after dusk. Attentive service, clear guidance, and gentle touches make stays easy.`, image: IMAGE_3, location: "Ottawa, Canada", rating: 4.5, price: 240 },
  { name: "Coastal Quebec City Plaza", description: `Within the old walls, Coastal Quebec City Plaza overlooks the St. Lawrence and peaked rooftops. Fireplace suites, deep soaking tubs, and down comforters make winters inviting; balconies catch summer light. The bistro serves Québécois classics with crisp cider; the bar pours ice wines. A compact spa and sauna ease travel weariness. Festivals, lanes, and viewpoints are moments away. Historic charm meets mindful modern comfort.`, image: IMAGE_4, location: "Quebec City, Canada", rating: 4.5, price: 240 },
  { name: "Heritage Paris Palace", description: `On the Left Bank, Heritage Paris Palace brings literary charm to elegant salons and restful rooms. Mornings begin with flaky pastries and ripe fruit; afternoons drift into a tea service under crystal light. Suites pair antique touches with modern bedding, powerful showers, and silent climate control. The bar favors Champagne and classic cocktails; the brasserie celebrates market finds. Museums, bookshops, and river walks sit nearby. Refined, intimate, and unmistakably Parisian, it invites deep rest between unhurried days.`, image: IMAGE_1, location: "Paris, France", rating: 4.7, price: 200 },
  { name: "Panorama Tokyo Retreat", description: `Panorama Tokyo Retreat captures neon views and metropolitan energy, then hushes them at the door. Rooms are minimal and cocooning, with soft tatami tones, deep tubs, and blackout tranquility. The café serves precision‑brewed coffee; the restaurant threads Japanese flavors through quietly elegant plates. A small gym, onsen‑style baths, and a meditation room support unhurried routines. Rail links, shops, and parks lie minutes away. Calm, precise, and restorative—a steady anchor in a dazzling city.`, image: IMAGE_2, location: "Tokyo, Japan", rating: 4.8, price: 310 },
];

// Static locations (max 8 countries)
const locations = [
  { name: "France" },
  { name: "Australia" },
  { name: "Japan" },
  { name: "United States" },
  { name: "Italy" },
  { name: "Spain" },
  { name: "United Kingdom" },
  { name: "Canada" },
];

const seedDatabase = async () => {
  try {
    // Connect to database
    await connectDB();

    // Clear existing data

    await Hotel.deleteMany({});
    await Location.deleteMany({});

    console.log("Cleared existing data");

    // Insert locations
    const createdLocations = await Location.insertMany(locations);
    console.log(`Created ${createdLocations.length} locations`);

    // Insert hotels
    // Map original hotels array to a new array with the additional embedding field generated via generateEmbedding

    const hotelsWithEmbedding = hotels.map(async (hotel) => {
      console.log("Embedding hotel", hotel.name);
      
      const embedding = await generateEmbedding(
        `${hotel.name} ${hotel.description} ${hotel.location} ${hotel.price}`
      );
      return { ...hotel, embedding };
    });

    const toBeCreatedHotels = await Promise.all(hotelsWithEmbedding);

    let createdHotels = await Hotel.insertMany(toBeCreatedHotels);
    console.log(`Created ${createdHotels.length} hotels`);

    // Create Stripe product with default price for each hotel (sequential with fixed delay)
    const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
    for (const hotel of createdHotels) {
      try {
        const product = await stripe.products.create({
          name: hotel.name,
          description: hotel.description,
          default_price_data: {
            unit_amount: Math.round(hotel.price * 100),
            currency: "usd",
          },
        });
        const defaultPriceId =
          typeof product.default_price === "string"
            ? product.default_price
            : (product.default_price as any)?.id;
        await Hotel.findByIdAndUpdate(
          hotel._id,
          { stripePriceId: defaultPriceId },
          { new: true }
        );
      } catch (e) {
        console.warn(`Stripe setup failed for hotel ${hotel.name}:`, e);
      }
      // simple interval to avoid bursts
      await sleep(300);
    }
    console.log("Database seeded successfully!");

    // Display summary
    console.log("\n=== SEED SUMMARY ===");
    console.log(`Locations: ${createdLocations.length}`);
    console.log(`Hotels: ${createdHotels.length}`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

// Run the seed script
seedDatabase();


